Add type hints
Convex-Dev/convex-api-py pull request #2
Opened 2023-03-07 10:06 UTC by superstructor

Adding more type safety esp for consuming projects of the APIs. Using e.g. `Union[Account, int, str]` instead of `Account | int | str` etc so that it should remain compatible with older (3.6?) Python releases.

2023-03-08 01:52 UTC, billbsing requested changes
looks, good but the Lint checks are failing

2023-03-10 01:15 UTC, billbsing commented on convex_api/utils.py
> -    if text:
`if text:` is testing for text == None and len(text) == 0
`if text is None` is only testing for == None not len(text) == 0

2023-03-17 04:41 UTC, billbsing approved these changes
looks good

2023-03-17 04:41 UTC, billbsing commented on convex_api/api.py
You can get rid of the 'language' option, since Convex  in the past we had convex-script but now there is only one language

2023-03-22 09:47 UTC, superstructor commented on convex_api/api.py
Thanks. Removed.

2023-05-05 09:54 UTC, merged